//!! generated by tsickle from marketing/glue/lib/banner/constants.ts
/**
 * @fileoverview Constants used by the Banner component.
 */
declare enum CssClasses {
    BANNER_CLOSE_BUTTON = "glue-banner__close-btn",
    BANNER_HIDDEN = "glue-banner--hidden"
}
declare enum Numbers {
    BANNER_CLOSE_DELAY = 300
}
export { CssClasses, Numbers };
