//!! generated by tsickle from marketing/glue/lib/carousel/constants.ts
/**
 * @fileoverview Constants used by the Carousel component.
 */
declare enum CssClasses {
    LIST = "glue-carousel__list",
    VIEWPORT = "glue-carousel__viewport",
    BUTTON = "glue-carousel__button",
    BUTTON_PREV = "glue-carousel__button--prev",
    BUTTON_NEXT = "glue-carousel__button--next",
    ITEM = "glue-carousel__item",
    NAVIGATION = "glue-carousel__navigation",
    NAVIGATION_DOT = "glue-carousel__dot",
    ACTIVE = "glue-is-active",
    INACTIVE = "glue-is-inactive",
    PEEK_OUT = "glue-carousel--peek-out",
    HAS_NAVIGATION = "glue-carousel--has-navigation",
    CARDS = "glue-carousel--cards",
    DISABLE_GRAB = "glue-carousel__list--disable-grab"
}
declare enum Numbers {
    /**
     * A threshold value that corresponds to the Carousel viewport width.
     * It is factor, a value between 0 to 1.
     * E.g. drag threshold is 0.2 * containerWidth.
     */
    DRAG_THRESHOLD = 0.2,
    /**
     * The minimum distance that the user needs to move before the carousel
     * recognizes the gesture as a drag (rather than a click, etc).
     */
    DRAGSTART_THRESHOLD_PX = 10,
    /**
     * When determining the number of slides per page, if the resulting value is
     * within this range from an integer, round up, otherwise round down.
     * E.g. 1.9999962591720426 => 2
     */
    ROUNDING_THRESHOLD = 0.05,
    /**
     * Distance in pixels for the card carousel to peek out on small viewport
     */
    PEEK_DISTANCE = 24
}
declare enum Strings {
    DATA_DOT = "dot",
    DATA_NAVIGATION_LABEL = "glueCarouselNavigationLabel",
    NAVIGATION_LABEL_DEFAULT = "Selected tab $glue_carousel_page_number$ of $glue_carousel_page_total$",
    NAVIGATION_LABEL_NUMBER_VAR_NAME = "$glue_carousel_page_number$",
    NAVIGATION_LABEL_TOTAL_VAR_NAME = "$glue_carousel_page_total$",
    RTL = "rtl",
    SLIDE_CHANGE = "gluecarouselslidechange",
    TRANSITION_NONE = "none"
}
export { CssClasses, Numbers, Strings };
